### PR TITLE
Fix bugs: single_list.c has some grammer errors.

### PR DESCRIPTION
**Pull request by SuperChenSSS**

### CODE REVIEW

**Comment by RichardWeiYang** [comment]
I don't see build error on Mac and Linux. Which error message you see?

It would be better to list the message and platform for these errors.

BTW, add ";" at the end of a function is not a good practice even there is no warning/error.

**Comment by SuperChenSSS** [comment]
@RichardWeiYang I understand. I was using gcc to build the target file. In the C programming language, the 'struct' grammar must end with ';'
see this link:https://www.geeksforgeeks.org/structures-c/
I hope that you understand. If you pass the compiling, probably means that the compiler has optimized the code for you. It doesn't mean that there is no error.

**Comment by SuperChenSSS** [comment]
@RichardWeiYang Ops, I have misunderstood... Thx, the ';' shouldn't be there.
I thought it is a 'struct' lol :)

**Comment by RichardWeiYang** [comment]
...

**Pull request merged**
